### ISSUE TITLE
k8s_v1_secret outputs the secrets

### ISSUE THREAD

**Issue by derfred** [ansible/ansible-kubernetes-modules#17]
Using the ```k8s_v1_secret``` module results output like this:
```
changed: [host] => (item={'name': 'secret-name', 'user': 'username', 'pass': 'password'})
```
This output is also saved in the logs. I think the secrets should be hidden.

**Comment by awiddersheim** [comment]
Ansible has a `no_log` option that should help with this.

http://docs.ansible.com/ansible/latest/faq.html#how-do-i-keep-secret-data-in-my-playbook

**Comment by fabianvf** [comment]
x-posted to openshift/openshift-restclient-python#117
