### ISSUE TITLE
APB Failing due to module error

### ISSUE THREAD

**Issue by goindwalia** [ansible/ansible-kubernetes-modules#36]
I am running Ansible Playbook Bundle on Minikube 1.9.4 using Ansible Service broker.  The APB rds-postgres-apb is failing due to 

`"module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible__Ri7Yp/ansible_module_k8s_v1_service.py\", line 360, in <module>\n    main()\n  File \"/tmp/ansible__Ri7Yp/ansible_module_k8s_v1_service.py\", line 354, in main\n    module.execute_module()\n  File \"/tmp/ansible__Ri7Yp/ansible_modlib.zip/ansible/module_utils/k8s_common.py\", line 199, in execute_module\n  File \"/tmp/ansible__Ri7Yp/ansible_modlib.zip/ansible/module_utils/k8s_common.py\", line 253, in _create\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\ufffd' in position 171: ordinal not in range(128)\n"`

any help will be appreciated

**Comment by fabianvf** [comment]
closed in favor of https://github.com/ansibleplaybookbundle/rds-postgres-apb/issues/2
